name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: Upload
      uses: contentful/actions-app-deploy@v1
      if: github.ref == 'refs/heads/main'
      with:
        organization-id: ${{ secrets.ORGANIZATION_ID }}
        app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
        access-token: ${{ secrets.ACCESS_TOKEN }}
        folder: dist